### Configuration
@baseUrl = http://localhost:8000/api
@contentType = application/json

### Register User
POST {{baseUrl}}/register
Content-Type: {{contentType}}

{
    "name": "your_name",
    "email": "your_email@example.com",
    "password": "password123",
    "password_confirmation": "password123"
}

### Login
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "your_email@example.com",
    "password": "password123"
}

### token
@token= {{login.response.body.access_token}}

### Me
GET {{baseUrl}}/me
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Logout
POST {{baseUrl}}/logout
Authorization: Bearer {{token}}
Content-Type: {{contentType}}